fix: add a ban on commits in mine and development, add scripts to run prettier, eslint, jest

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,13 @@
 #!/usr/bin/env sh
-# . "$(dirname -- "$0")/_/husky.sh"
+. "$(dirname -- "$0")/_/husky.sh"
 
-# branch="$(git rev-parse --abbrev-ref HEAD)"
+branch="$(git rev-parse --abbrev-ref HEAD)"
 
-# if [ "$branch" = "master" ]; then
-#   echo "You can't commit directly to master branch"
-#   exit 1
-# fi
+if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
+  echo "You can't commit directly to main or develop branch"
+  exit 1
+fi
 
+npm run format
+npm run lint
 npm test
-npx eslint
